application: gooroo-dev
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.(gif|png|jpg|ico|js|css|map|mp4|ico))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|map|mp4|ico))

- url: .*
  script: main.py
